package uz.nodirbek.receiptdelivery.ui

enum class Screen {
    ONB1, ONB2, AUTH_PHONE, AUTH_OTP, AUTH_PROFILE, DISTRICT, OFFZONE, HOME, SEARCH, RECIPE, CART, CHECKOUT, TRACKING, COOKING, PROFILE, ORDER_HISTORY, ADDRESSES, SETTINGS
}
